language: php
php:
    - 5.5
    - 5.4
    - hhvm
    
install:
    - cp -r app/view vendor/anax/mvc/app/
    - cp -r webroot/config_with_app.php vendor/anax/mvc/webroot/config_with_app.php

script: 
    - phpunit --bootstrap test/config.php test



