language: php
php:
    - 5.5
    - 5.4
    - hhvm

before_script:
    - composer install
    - wget https://scrutinizer-ci.com/ocular.phar
    
install:
    - composer require anax/mvc
    - cp -r app/view vendor/anax/mvc/app/
    - cp -r webroot/config_with_app.php vendor/anax/mvc/webroot/config_with_app.php

script: 
    - phpunit --bootstrap test/config.php test
    - phpunit --bootstrap test/config.php --coverage-clover coverage.clover test

after_script:
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

